name: Lint
on: [push, pull_request]
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check dependencies
        run: |
          go mod tidy
          git diff --exit-code go.mod

      - name: Lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: v1.52
