name: Vulnerability Check
on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]
  schedule:
    - cron: "0 0 * * 0"
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck -v ./...
